
                ifndef _OBJECT_UTILITIES_INCLUDE_
                define _OBJECT_UTILITIES_INCLUDE_

                module Utilities
                include "AddressObject.asm"
                include "GetObjectIDByAddress.asm"
                include "UpdateChunkByPosition.asm"
                include "IncrementCadencePassIDs.asm"
                include "GetCadencePassIdByChunk.asm"
                endmodule

                endif ; ~ _OBJECT_UTILITIES_INCLUDE_
