
                ifndef _CONST_GAME_DESIGN_
                define _CONST_GAME_DESIGN_
; настройки геймдизайна:
MOVEMENT_DEFAULT_SPEED          EQU 0x0038                                      ; базовые единицы движения за один "мировой тик"
MOVEMENT_DEFAULT_STEP_COST      EQU 0x0004                                      ; базовая стоимость четвертьпиксельного DDA-шага

                endif ; ~_CONST_GAME_DESIGN_
