
                ifndef _GRAPHICS_HEXAGON_NATURAL_LANDSCAPES_INCLUDE_
                define _GRAPHICS_HEXAGON_NATURAL_LANDSCAPES_INCLUDE_

                module NaturalLandscapes                                        ; природные ландшафты
                
                include "Grasslands/Include.inc"

                endmodule

                endif ; ~ _GRAPHICS_HEXAGON_NATURAL_LANDSCAPES_INCLUDE_
