                
                ifndef _AI_DIRECTOR_POPULATION_CONTROL_INCLUDE_
                define _AI_DIRECTOR_POPULATION_CONTROL_INCLUDE_

                ; контроль общей популяции групп директора
                ; ToDo:
                ;   - обойти существующие группы директора
                ;   - подсчитать количество активных групп и PopulationCost
                ;   - определить текущий PopulationLimit
                ;   - получить свободную часть лимита для нового спавна
                module PopulationControl
                
                endmodule

                endif ; ~_AI_DIRECTOR_POPULATION_CONTROL_INCLUDE_
