
                ifndef _MODULE_CHARACTERISTICS_LAUNCH_INCLUDE_
                define _MODULE_CHARACTERISTICS_LAUNCH_INCLUDE_

                module Launch
                include "Deploy.asm"
                include "Window.asm"
                include "InitSprites.asm"
                include "CharacteristicsInitialize.asm"
                endmodule

                endif ; ~_MODULE_CHARACTERISTICS_LAUNCH_INCLUDE_
