                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_0.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_0_offsets.bin", \
                    incbin "sprite_0_col_0.bin", \
                    incbin "sprite_0_col_1.bin", \
                    incbin "sprite_0_col_2.bin", \
                    incbin "sprite_0_col_3.bin", \
                    incbin "sprite_0_col_4.bin", \
                    incbin "sprite_0_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_1.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_1_offsets.bin", \
                    incbin "sprite_1_col_0.bin", \
                    incbin "sprite_1_col_1.bin", \
                    incbin "sprite_1_col_2.bin", \
                    incbin "sprite_1_col_3.bin", \
                    incbin "sprite_1_col_4.bin", \
                    incbin "sprite_1_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_2.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_2_offsets.bin", \
                    incbin "sprite_2_col_0.bin", \
                    incbin "sprite_2_col_1.bin", \
                    incbin "sprite_2_col_2.bin", \
                    incbin "sprite_2_col_3.bin", \
                    incbin "sprite_2_col_4.bin", \
                    incbin "sprite_2_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_3.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_3_offsets.bin", \
                    incbin "sprite_3_col_0.bin", \
                    incbin "sprite_3_col_1.bin", \
                    incbin "sprite_3_col_2.bin", \
                    incbin "sprite_3_col_3.bin", \
                    incbin "sprite_3_col_4.bin", \
                    incbin "sprite_3_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_4.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_4_offsets.bin", \
                    incbin "sprite_4_col_0.bin", \
                    incbin "sprite_4_col_1.bin", \
                    incbin "sprite_4_col_2.bin", \
                    incbin "sprite_4_col_3.bin", \
                    incbin "sprite_4_col_4.bin", \
                    incbin "sprite_4_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_5.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_5_offsets.bin", \
                    incbin "sprite_5_col_0.bin", \
                    incbin "sprite_5_col_1.bin", \
                    incbin "sprite_5_col_2.bin", \
                    incbin "sprite_5_col_3.bin", \
                    incbin "sprite_5_col_4.bin", \
                    incbin "sprite_5_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_6.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_6_offsets.bin", \
                    incbin "sprite_6_col_0.bin", \
                    incbin "sprite_6_col_1.bin", \
                    incbin "sprite_6_col_2.bin", \
                    incbin "sprite_6_col_3.bin", \
                    incbin "sprite_6_col_4.bin", \
                    incbin "sprite_6_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_7.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_7_offsets.bin", \
                    incbin "sprite_7_col_0.bin", \
                    incbin "sprite_7_col_1.bin", \
                    incbin "sprite_7_col_2.bin", \
                    incbin "sprite_7_col_3.bin", \
                    incbin "sprite_7_col_4.bin", \
                    incbin "sprite_7_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_8.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/Fog/sprite_8_offsets.bin", \
                    incbin "sprite_8_col_0.bin", \
                    incbin "sprite_8_col_1.bin", \
                    incbin "sprite_8_col_2.bin", \
                    incbin "sprite_8_col_3.bin", \
                    incbin "sprite_8_col_4.bin", \
                    incbin "sprite_8_col_5.bin"
