
                ifndef _CONST_PLAYER_ACTIONS_
                define _CONST_PLAYER_ACTIONS_
PLAYER_ACTION_NONE      EQU 0x00                                                ; отсутствуют действия
PLAYER_ACTION_SELECT    EQU 0x00                                                ; выбор
PLAYER_ACTION_CAST      EQU 0x00                                                ; каст заклинания

                endif ; ~_CONST_PLAYER_ACTIONS_
