
                ifndef _CONST_HERO_CLASSES_
                define _CONST_HERO_CLASSES_
Hero.Class:
.Druid          EQU 0x00                                                        ; друид
.Wizard         EQU 0x00                                                        ; волшебник
.Warlock        EQU 0x00                                                        ; колдун
.Witch          EQU 0x00                                                        ; вкдьма
.DeathKnight    EQU 0x00                                                        ; рыцарь смерти
.Overlord       EQU 0x00                                                        ; повелитель
.Necromancer    EQU 0x00                                                        ; некромант

                endif ; ~_CONST_HERO_CLASSES_
