
                ifndef _MODULE_WORLD_UI_HANDLER_INCLUDE_
                define _MODULE_WORLD_UI_HANDLER_INCLUDE_

                module Handler
                include "Layer_GameUI.asm"
                include "Layer_Minimap.asm"
                include "Layer_GameView.asm"
                include "Layer_GamePause.asm"
                include "Icon_Characteristics.asm"
                endmodule

                endif ; ~_MODULE_WORLD_UI_HANDLER_INCLUDE_
