
                ifndef _CHARACTERISTICS_INCLUDE_
                define _CHARACTERISTICS_INCLUDE_

                module Base

                include "Loop.asm"
                include "Interrupt.asm"
                include "Release.asm"
                include "Render/Include.inc"
                include "UI/Layers.inc"
                include "UI/Transition.asm"

                endmodule

                endif ; ~_CHARACTERISTICS_INCLUDE_
