
                ifndef _GRAPHICS_UI_GAMEPLAY_SCREEN_WORLD_FRAME_PACK_INCLUDE_
                define _GRAPHICS_UI_GAMEPLAY_SCREEN_WORLD_FRAME_PACK_INCLUDE_

                module World
                include "Pack_Frame.inc"
                include "Pack_Ornament.inc"
                ; include "Pack_FrameMinimap.inc"
                endmodule

                endif ; ~ _GRAPHICS_UI_GAMEPLAY_SCREEN_WORLD_FRAME_PACK_INCLUDE_
