
                ifndef _MACRO_INCLUDE_
                define _MACRO_INCLUDE_

                include "Debug.inc"
                include "Flags.inc"
                include "Mouse.inc"
                include "Assets.inc"
                include "Memory.inc"
                include "Memset.inc"
                include "Screen_.inc"
                include "Interrupt.inc"

                ; include "Config/Include.inc"
                include "Game/Include.inc"

                endif ; ~_MACRO_INCLUDE_
