
                ifndef _MACRO_GAME_INCLUDE_
                define _MACRO_GAME_INCLUDE_

                include "Game_View.inc"
                include "Game_Input.inc"
                include "Game_Render.inc"
                include "Game_Options.inc"
                include "Game_Interupt.inc"
                include "Game_MainLoop.inc"
                include "Game_MainMenu.inc"
                include "Game_HardInput.inc"
                include "Game_InputTimer.inc"
                include "Game_MainLoopCore.inc"

                include "Game_World.inc"

                endif ; ~_MACRO_GAME_INCLUDE_
