                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/grid.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/grid_offsets.bin", \
                    incbin "grid_col_0.bin", \
                    incbin "grid_col_1.bin", \
                    incbin "grid_col_2.bin", \
                    incbin "grid_col_3.bin", \
                    incbin "grid_col_4.bin", \
                    incbin "grid_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/outline.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/outline_offsets.bin", \
                    incbin "outline_col_0.bin", \
                    incbin "outline_col_1.bin", \
                    incbin "outline_col_2.bin", \
                    incbin "outline_col_3.bin", \
                    incbin "outline_col_4.bin", \
                    incbin "outline_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_1.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_1_offsets.bin", \
                    incbin "sprite_1_col_0.bin", \
                    incbin "sprite_1_col_1.bin", \
                    incbin "sprite_1_col_2.bin", \
                    incbin "sprite_1_col_3.bin", \
                    incbin "sprite_1_col_4.bin", \
                    incbin "sprite_1_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_2.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_2_offsets.bin", \
                    incbin "sprite_2_col_0.bin", \
                    incbin "sprite_2_col_1.bin", \
                    incbin "sprite_2_col_2.bin", \
                    incbin "sprite_2_col_3.bin", \
                    incbin "sprite_2_col_4.bin", \
                    incbin "sprite_2_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_3.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_3_offsets.bin", \
                    incbin "sprite_3_col_0.bin", \
                    incbin "sprite_3_col_1.bin", \
                    incbin "sprite_3_col_2.bin", \
                    incbin "sprite_3_col_3.bin", \
                    incbin "sprite_3_col_4.bin", \
                    incbin "sprite_3_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_4.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_4_offsets.bin", \
                    incbin "sprite_4_col_0.bin", \
                    incbin "sprite_4_col_1.bin", \
                    incbin "sprite_4_col_2.bin", \
                    incbin "sprite_4_col_3.bin", \
                    incbin "sprite_4_col_4.bin", \
                    incbin "sprite_4_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_6.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_6_offsets.bin", \
                    incbin "sprite_6_col_0.bin", \
                    incbin "sprite_6_col_1.bin", \
                    incbin "sprite_6_col_2.bin", \
                    incbin "sprite_6_col_3.bin", \
                    incbin "sprite_6_col_4.bin", \
                    incbin "sprite_6_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_7.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_7_offsets.bin", \
                    incbin "sprite_7_col_0.bin", \
                    incbin "sprite_7_col_1.bin", \
                    incbin "sprite_7_col_2.bin", \
                    incbin "sprite_7_col_3.bin", \
                    incbin "sprite_7_col_4.bin", \
                    incbin "sprite_7_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_8.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_8_offsets.bin", \
                    incbin "sprite_8_col_0.bin", \
                    incbin "sprite_8_col_1.bin", \
                    incbin "sprite_8_col_2.bin", \
                    incbin "sprite_8_col_3.bin", \
                    incbin "sprite_8_col_4.bin", \
                    incbin "sprite_8_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_9.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_9_offsets.bin", \
                    incbin "sprite_9_col_0.bin", \
                    incbin "sprite_9_col_1.bin", \
                    incbin "sprite_9_col_2.bin", \
                    incbin "sprite_9_col_3.bin", \
                    incbin "sprite_9_col_4.bin", \
                    incbin "sprite_9_col_5.bin"

                CREATE_HEX_SPRITE \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_10.bin", \
                    savebin "Builder/Assets/Graphics/Original/Hex/NaturalLandscapes/Grasslands/sprite_10_offsets.bin", \
                    incbin "sprite_10_col_0.bin", \
                    incbin "sprite_10_col_1.bin", \
                    incbin "sprite_10_col_2.bin", \
                    incbin "sprite_10_col_3.bin", \
                    incbin "sprite_10_col_4.bin", \
                    incbin "sprite_10_col_5.bin"

