
                ifndef _CHARACTER_PATH_INCLUDE_
                define _CHARACTER_PATH_INCLUDE_

                module Path
                include "Distance.asm"
                include "Direction.asm"
                include "PathInitialize.asm"
                ; include "ReificationHeroPath.asm"                               ; DEPRECATED
                endmodule

                endif ; ~ _CHARACTER_PATH_INCLUDE_
