
                ifndef _MODULE_WORLD_LAUNCH_INCLUDE_
                define _MODULE_WORLD_LAUNCH_INCLUDE_

                module Launch
                include "Deploy.asm"
                include "InitSprites.asm"
                include "CreateTables.asm"
                include "WaitProgress.asm"
                include "CreateTexture.asm"
                include "GameplayWindow.asm"
                include "WorldInitialize.asm"
                endmodule

                endif ; ~_MODULE_WORLD_LAUNCH_INCLUDE_
