
                ifndef _PARTICIPANT_INCLUDE_
                define _PARTICIPANT_INCLUDE_

                module Participant

                include "Append.asm"
                include "Add_Player.asm"
                include "Add_Character.asm"
                include "Remove_Player.asm"
                include "Remove_Character.asm"

                endmodule

                endif ; ~_PARTICIPANT_INCLUDE_
