
                ifndef _GRAPHICS_UI_GAME_WORLD_PACK_INCLUDE_
                define _GRAPHICS_UI_GAME_WORLD_PACK_INCLUDE_

                module Graphics
                module Game_World

                include "Pack_Frame.inc"
                include "Pack_Ornament.inc"
                ; include "Pack_FrameMinimap.inc"

                endmodule
                endmodule

                endif ; ~ _GRAPHICS_UI_GAME_WORLD_PACK_INCLUDE_
