
                ifndef _BUFFERS_UTILITIES_INCLUDE_
                define _BUFFERS_UTILITIES_INCLUDE_

                module Utilities
                include "GetAdrArrayByCoord.asm"
                include "GetHextileIDByCoord.asm"
                include "GetRenderBufferByIndex.asm"
                include "GetRenderIndexByCoordinates.asm"
                endmodule

                endif ; ~_BUFFERS_UTILITIES_INCLUDE_
