
                ifndef _GRAPHICS_TILE_BIOME_GRASS_SAND_
                define _GRAPHICS_TILE_BIOME_GRASS_SAND_
Grass_Sand:
.Grass          incbin "Grass.spr"                                              ; полностью трава
.Sand           incbin "Sand.spr"                                               ; полностью песок
.GGGS           incbin "Grass_Sand_0.spr"                                       ; трава "левый-верхний"
.GGSS           incbin "Grass_Sand_1.spr"                                       ; трава "верхний"
.GGSG           incbin "Grass_Sand_2.spr"                                       ; трава "правый-верхний"
.GSGS           incbin "Grass_Sand_3.spr"                                       ; трава "левый"
.SGSG           incbin "Grass_Sand_4.spr"                                       ; трава "правый"
.GSGG           incbin "Grass_Sand_5.spr"                                       ; трава "левый-нижний"
.SSGG           incbin "Grass_Sand_6.spr"                                       ; трава "нижний"
.SGGG           incbin "Grass_Sand_7.spr"                                       ; трава "правый-нижний"
.SSSG           incbin "Sand_Grass_0.spr"                                       ; песок "левый-верхний"
.SSGS           incbin "Sand_Grass_1.spr"                                       ; песок "правый-верхний"
.SGSS           incbin "Sand_Grass_2.spr"                                       ; песок "левый-нижний"
.GSSS           incbin "Sand_Grass_3.spr"                                       ; песок "правый-нижний"
.Forest_0       incbin "Forest_0.spr"
.Forest_1_0     incbin "Forest_1_0.spr"
.Forest_1_1     incbin "Forest_1_1.spr"

                endif ; ~ _GRAPHICS_TILE_BIOME_GRASS_SAND_
