
                ifndef _CONST_INCLUDE_
                define _CONST_INCLUDE_

                include "TR-DOS.inc"
                include "ZX-Color.inc"
                
                include "Memory/Include.inc"
                include "Assets/Include.inc"

                include "Cursor.inc"
                include "Interrupt.inc"

                include "Game/Include.inc"
                include "Input/Include.inc"

                endif ; ~_CONST_INCLUDE_
