
                ifndef _CONST_INCLUDE_
                define _CONST_INCLUDE_

                include "TR-DOS.inc"
                include "ZX-Color.inc"
                
                include "Memory/Include.inc"
                include "Assets/Include.inc"

                include "AStar.inc"
                include "Event.inc"
                include "Setup.inc"
                include "Cursor.inc"
                include "Sprite.inc"
                include "Gameplay.inc"
                include "SaveSlot.inc"
                include "Interrupt.inc"

                include "Map/Include.inc"
                include "Game/Include.inc"
                include "Input/Include.inc"
                include "Object/Include.inc"
                include "Player/Include.inc"

                endif ; ~_CONST_INCLUDE_
