
                ifndef _CONST_PARTICLE_
                define _CONST_PARTICLE_
TARGET_PARTICLE_SIZE    EQU 12                                                  ; размер структуры FTargetParticle
MAX_TARGET_PARTICLE     EQU 255                                                 ; максимальное количество частиц 'нацеливания'
                                                                                ; значение уменьшено на еденицу, т.к. мб 0 элементов

                endif ; ~_CONST_PARTICLE_
