
                ifndef _MODULE_WORLD_INCLUDE_
                define _MODULE_WORLD_INCLUDE_

                ; ToDo: в дальнейшем потребуется разного рода загрузки ассетов,
                ;       что повлечёт за собой сназала загрузку Deploy а после запуск мира

                include "Launch.asm"                                            ; (0)
                include "Source/World/Include.inc"

                endif ; ~_MODULE_WORLD_INCLUDE_
