
                ifndef _CONST_MEMORY_INCLUDE_
                define _CONST_MEMORY_INCLUDE_

                include "Memory.inc"
                include "MemoryWrapper.inc"
                include "MemoryMap_Page_0.inc"
                include "MemoryMap_Page_1.inc"
                include "MemoryMap_Page_2.inc"
                include "MemoryMap_Page_3.inc"
                include "MemoryMap_Page_4.inc"
                include "MemoryMap_Page_5.inc"
                include "MemoryMap_Page_6.inc"
                include "MemoryMap_Page_7.inc"
                include "MemoryMap_Modules.inc"

                endif ; ~_CONST_MEMORY_INCLUDE_
