
                ifndef _CONST_MEMORY_MAP_PAGE_4_
                define _CONST_MEMORY_MAP_PAGE_4_

                ;   +-------+------------------------------------------+-------+
                ;   | #C000 |                                          | #0000 |
                ;   +-------+------------------------------------------+-------+

                module Page
                endmodule

                module Size
                endmodule

                module Adr
                endmodule

                endif ; ~_CONST_MEMORY_MAP_PAGE_4_
