
                ifndef _GRAPHICS_HEXAGON_INCLUDE_
                define _GRAPHICS_HEXAGON_INCLUDE_

                module Hexagon
                
                include "Fog/Include.inc"
                include "Build/Include.inc"
                include "ColdRegions/Include.inc"
                include "NaturalLandscapes/Include.inc"
                include "SpecialFormations/Include.inc"
                include "WaterRelatedLandscapes/Include.inc"

                endmodule

                endif ; ~ _GRAPHICS_HEXAGON_INCLUDE_
