
                ifndef _STRUCTS_UI_INCLUDE_
                define _STRUCTS_UI_INCLUDE_

                include "Layer.inc"
                include "Runtime.inc"

                ; структуры описывающие UI объекты и их поведение
                include "Animation.inc"
                include "BehaviorPhase.inc"
                include "Settings_Flags.inc"
                include "Settings_Progress.inc"
                include "Settings_AnimationRange.inc"

                endif ; ~_STRUCTS_UI_INCLUDE_
