
                ifndef _CONST_OBJECT_UI_
                define _CONST_OBJECT_UI_
; значения для поля FObject.Sprite
ARROW_PATH_TYPE_BIT EQU 0x07                                                    ; флаг типа спрайта
                                                                                ;   0 - проходимый
                                                                                ;   1 - непроходимый
                endif ; ~_CONST_OBJECT_UI_
