
                ifndef _WORLD_RENDER_OBJECT_INCLUDE_
                define _WORLD_RENDER_OBJECT_INCLUDE_

                module Object
                include "Draw.asm"
                include "UI/Include.inc"
                include "Hero/Include.inc"
                include "ObjectsInView.asm"
                include "Simple/Include.inc"
                include "ObjectDirtyEnvironment.asm"
                endmodule

                endif ; ~_WORLD_RENDER_OBJECT_INCLUDE_
