
                ifndef _STRUCTS_HERO_SECONDARY_SKILL_
                define _STRUCTS_HERO_SECONDARY_SKILL_

                struct FSecondarySkill                                          ; вторичные навыки героя                                        [байт]

                ; добавить слоты под вторичные навыки
                
                ends

                endif ; ~_STRUCTS_HERO_SECONDARY_SKILL_
