
                ifndef _STRUCTS_HERO_COMBAT_STATES_
                define _STRUCTS_HERO_COMBAT_STATES_

                struct FCombatStates                                            ; боевые состояния                                              [байт]
Luck            DB #00                                                          ; удача
Morale          DB #00                                                          ; мораль

                ends

                endif ; ~_STRUCTS_HERO_COMBAT_STATES_
