
                ifndef _STRUCTS_CHARACTER_INCLUDE_
                define _STRUCTS_CHARACTER_INCLUDE_

                include "Character_Equipment.inc"
                include "Character_CombatStates.inc"
                include "Character_PrimarySkill.inc"
                include "Character_SecondarySkill.inc"
                include "Character.inc"

                endif ; ~_STRUCTS_CHARACTER_INCLUDE_
