
                ifndef _ASSETS_PACKING_GRAPHICS_INCLUDE_
                define _ASSETS_PACKING_GRAPHICS_INCLUDE_

                module Graphics
                include "Original/UI/Include.inc"                               ; 
                include "Original/Font/Include.inc"                             ; 
                include "Original/Hero/Include.inc"                             ; ASSETS_ID_HERO_PACK
                include "Original/Cursor/Include.inc"                           ; ASSETS_ID_CURSOR_PACK
                include "Original/Hex/Include.inc"                              ; ASSETS_ID_HEX_XXXX
                endmodule

                endif ; ~_ASSETS_PACKING_GRAPHICS_INCLUDE_
