
                ifndef _ASSETS_PACKING_GRAPHICS_INCLUDE_
                define _ASSETS_PACKING_GRAPHICS_INCLUDE_

                include "Original/Tile/Biomes/Include.inc"                      ; ASSETS_ID_TILE_BIOME_GRASS_SAND
                include "Original/Cursor/Include.inc"                           ; ASSETS_ID_CURSOR_PACK
                include "Original/Hero/Include.inc"                             ; ASSETS_ID_HERO_PACK
                include "Original/GraphPack/Include.inc"

                endif ; ~_ASSETS_PACKING_GRAPHICS_INCLUDE_
