
                ifndef _GRAPHICS_UI_PROGRESS_PACK_INCLUDE_
                define _GRAPHICS_UI_PROGRESS_PACK_INCLUDE_

                module Progress
                include "Pack_Strip.inc"
                include "Pack_Stages.inc"
                include "Pack_Progress.inc"
                include "WorldTreeSymbol/Pack.inc"
                endmodule

                endif ; ~ _GRAPHICS_UI_PROGRESS_PACK_INCLUDE_
