
                ifndef _GRAPHICS_UI_GAMEPLAY_OVERLAY_FACE_OF_HEROES_INCLUDE_
                define _GRAPHICS_UI_GAMEPLAY_OVERLAY_FACE_OF_HEROES_INCLUDE_

                module FaceOfHeroes
                include "Full/Include.inc"
                include "Small/Include.inc"
                include "Frame/Include.inc"
                endmodule

                endif ; ~ _GRAPHICS_UI_GAMEPLAY_OVERLAY_FACE_OF_HEROES_INCLUDE_
