
                ifndef _TICK_UTILS_INCLUDE_
                define _TICK_UTILS_INCLUDE_

                module Utils
                module Movement

                include "Movement.asm"

                endmodule

                module Reconnaissance

                include "Reconnaissance.asm"

                endmodule
                endmodule

                endif ; ~_TICK_UTILS_INCLUDE_
