
                ifndef _CONST_CHARACTER_REPRESENTATION_
                define _CONST_CHARACTER_REPRESENTATION_

; общие индексы изображений персонажей
Character.Name:
.Druid          EQU #00                                                         ; друид
.Wizard         EQU #01                                                         ; волшебник

; идентификаторы представления персонажей в мире
Character.Appearance:
.Druid          EQU #00                                                         ; друид
.Wizard         EQU #01                                                         ; волшебник

                endif ; ~_CONST_CHARACTER_REPRESENTATION_
