
                ifndef _TICK_OBJECT_UI_INCLUDE_
                define _TICK_OBJECT_UI_INCLUDE_

                include "Behavior.inc"

                include "None.asm"
                include "Default.asm"
                include "SetFlags.asm"
                include "MarkDirty.asm"
                include "ResetFlags.asm"
                include "UpdateHover.asm"
                include "UpdateAnchor.asm"
                include "UpdateLifetime.asm"
                include "UpdateProgress.asm"
                include "SetAnimationRange.asm"

                endif ; ~_TICK_OBJECT_UI_INCLUDE_
