
                ifndef _STRUCT_AI_POPULATION_DIRECTOR_
                define _STRUCT_AI_POPULATION_DIRECTOR_

                struct FAIDirector
SpawnPointNum   DB #00                                                          ; количество "точек спавна"
                DS 3, 0                                                         ; dummy
                ends

                endif ; ~_STRUCT_AI_POPULATION_DIRECTOR_
