
                ifndef _STRUCTS_INCLUDE_
                define _STRUCTS_INCLUDE_

                include "Value.inc"
                include "Disk.inc"
                include "Vector8.inc"
                include "Vector16.inc"
                include "Address.inc"
                include "Assets.inc"
                
                include "Tick.inc"
                include "Size.inc"
                include "Keys.inc"
                include "Sprite.inc"
                include "Item_ID.inc"
                include "WorldInfo.inc"
                include "Map/Include.inc"
                include "Game_State.inc"
                include "Game_Config.inc"
                include "Game_Session.inc"
                include "Object/Include.inc"
                
                include "Hero/Include.inc"
                include "Player/Include.inc"

                endif ; ~_STRUCTS_INCLUDE_
