
                ifndef _STRUCTS_INCLUDE_
                define _STRUCTS_INCLUDE_

                include "Value.inc"
                include "Disk.inc"
                include "Vector8.inc"
                include "Vector16.inc"
                include "Address.inc"
                include "Assets.inc"
                include "Cursor.inc"
                
                include "Tick.inc"
                include "Size.inc"
                include "Keys.inc"
                ; include "Event.inc"                                             ; DEPRECATE
                include "Item_ID.inc"
                include "WorldInfo.inc"
                include "SpriteClipping.inc"
                include "SpriteNotClipping.inc"
                
                include "UI.inc"
                include "Map/Include.inc"
                include "SaveSlot.inc"

                include "Game_State.inc"
                include "Game_Config.inc"
                include "Hard_Config.inc"
                include "Game_Session.inc"

                include "Hero/Include.inc"
                include "Player/Include.inc"
                include "Object/Include.inc"

                endif ; ~_STRUCTS_INCLUDE_
