
                ifndef _STRUCTS_TICK_
                define _STRUCTS_TICK_

                struct FTick
Scroll          DB #00                                                          ; скролл карты
Tile            DB #00                                                          ; тайлы
Hero            DB #00                                                          ; герой
Objects         DB #00                                                          ; объекты
                ends

                endif ; ~_STRUCTS_TICK_
