
                ifndef _STRUCT_OBJECT_UI_
                define _STRUCT_OBJECT_UI_

                struct FObjectUI                                                ; объект - элетент UI                                       [байт]
Super           FObject                                                         ; базовый класс объекта                                     [14 байт]

                ends

                endif ; ~_STRUCT_OBJECT_UI_
