
                ifndef _STRUCT_OBJECT_DECAL_
                define _STRUCT_OBJECT_DECAL_

                struct FObjectDecal                                             ; объект - элемент декаль                                   [18 байт]
Layer           FLayerObject                                                    ; базовый класс объекта слоя                                [18 байт]
                ends

                endif ; ~_STRUCT_OBJECT_DECAL_
