
                ifndef _STRUCT_OBJECT_CONSTRUCTION_
                define _STRUCT_OBJECT_CONSTRUCTION_

                struct FObjectConstruction                                      ; объект - постройка                                        [байт]
Super           FObject                                                         ; базовый класс объекта                                     [9 байт]
                ends

                endif ; ~_STRUCT_OBJECT_CONSTRUCTION_
