                
                ifndef _AI_DIRECTOR_DISTANCE_MAP_INCLUDE_
                define _AI_DIRECTOR_DISTANCE_MAP_INCLUDE_

                module DistanceMap
                include "Build.asm"
                include "Launch.asm"
                include "Initialize.asm"
                include "UpdateFromNeighbor.asm"
                endmodule

                endif ; ~_AI_DIRECTOR_DISTANCE_MAP_INCLUDE_
