
                ifndef _GRAPHICS_UI_CHARACTERISTICS_INCLUDE_
                define _GRAPHICS_UI_CHARACTERISTICS_INCLUDE_

                module Characteristics
                include "Screen/PaperDoll/Pack_PaperDoll_Male.inc"              ; ASSETS_ID_UI_PAPER_DOLL_MALE_PACK
                include "Screen/PaperDoll/Pack_PaperDoll_Female.inc"            ; ASSETS_ID_UI_PAPER_DOLL_FEMALE_PACK
                endmodule

                endif ; ~ _GRAPHICS_UI_CHARACTERISTICS_INCLUDE_
