
                ifndef _STRUCTS_PLAYER_ACTIONS_
                define _STRUCTS_PLAYER_ACTIONS_
                
                struct FPlayerActions                                           ; действия игрока
SelectedHeroID  DB #00                                                          ; ID выбранный герой
Action          DB #00                                                          ; действие
                ends

                endif ; ~_STRUCTS_PLAYER_ACTIONS_
