
                ifndef _ASSETS_PACKING_CODE_INCLUDE_
                define _ASSETS_PACKING_CODE_INCLUDE_

                include "Original/Kernel/Pack_Kernel.inc"                       ; ASSETS_ID_KERNEL
                include "Original/Core/Pack.inc"                                ; ASSETS_ID_CORE
                include "Original/Pages/Pack_Page0.inc"                         ; ASSETS_ID_PAGE_0
                include "Original/MAP/Pack.inc"                                 ; ASSETS_ID_MAP
                include "Original/World/Pack.inc"                               ; ASSETS_ID_WORLD

                endif ; ~_ASSETS_PACKING_CODE_INCLUDE_
